version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: postgres13
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=chatDB
      - TZ=${TZ}
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
        PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
        - ${PGADMIN_PORT}:80
    depends_on:
        - postgres